import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Hero from '../components/WebMain/Hero'
import WhatWeOffer from '../components/WebMain/WhatWeOffer'
import BookNow from '../components/WebMain/BookNow'
import Popular from '../components/WebMain/Popular'
import GalleryImages from '../components/WebMain/GalleryImages'

import Footer from '../components/Footer'
import About from '../components/WebMain/About'

const Home = () => {
  return (
    <div>
      <Head>
        <title>CP Party Rental</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Navbar />

      <Hero />

      <WhatWeOffer />

      <BookNow />

      {/* <Popular />*/}
      <About />
      <GalleryImages />
      <Footer />
    </div>
  )
}

export default Home
